version: 2.1
jobs:
    build:
        machine:
            image: ubuntu-1604:202004-01
        steps:
            - checkout
            - run: curl http://www.google.com/
            - run: make build

    deploy_staging:
        machine:
            image: ubuntu-1604:202004-01
        steps:
            - checkout
            - add_ssh_keys
            - run:
                  name: Deploy on staging server
                  command: DEPLOY_HOSTNAME=$STAGING_HOSTNAME DEPLOY_PORT=$STAGING_PORT VERSION="5.0" make deploy

    deploy_production:
        machine:
            image: ubuntu-1604:202004-01
        steps:
            - checkout
            - add_ssh_keys
            - run:
                  name: Deploy on production server
                  command: DEPLOY_HOSTNAME=$PROD_HOSTNAME DEPLOY_PORT=$PROD_PORT VERSION="5.0" make deploy

workflows:
    version: 2
    pull_request:
        jobs:
            - build:
                  filters:
                      branches:
                          ignore:
                              - master

    deployment:
        jobs:
            - deploy_staging:
                  filters:
                      branches:
                          only: master
            - approve_to_deploy_in_production:
                  type: approval
                  requires:
                      - deploy_staging
            - deploy_production:
                  requires:
                      - approve_to_deploy_in_production
